name: FriendMap
options:
  bundleIdPrefix: com.friendmap
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

packages:
  Supabase:
    url: https://github.com/supabase/supabase-swift
    from: "2.5.1"

settings:
  base:
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    INFOPLIST_FILE: FriendMap/Info.plist

targets:
  FriendMap:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: FriendMap
        excludes:
          - "**/.DS_Store"
    dependencies:
      - package: Supabase
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.alexdamore.friendmap
        INFOPLIST_FILE: FriendMap/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0.0
        GENERATE_INFOPLIST_FILE: false
        SWIFT_EMIT_LOC_STRINGS: true
    info:
      path: FriendMap/Info.plist
      properties:
        CFBundleDisplayName: FriendMap
        CFBundleName: FriendMap
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UILaunchScreen:
          UIColorName: ""
          UIImageName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

